### ISSUE TITLE
run_exports missing in cuda-cupti-dev 12.0.*

### ISSUE THREAD

**Issue by traversaro** [conda-forge/cuda-cupti-feedstock#14]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

The issue in https://github.com/conda-forge/cuda-cupti-feedstock/issues/9 was fixed in https://github.com/conda-forge/cuda-cupti-feedstock/pull/10 , however it was fixed for cuda-cupti-dev 12.4.* . However, the conda-forge pinning pins the cuda libraries to 12.0.*, so the fix is not there. 

I wonder if you would consider creating a branch `v12.0` so that I can create a PR to also fix the problem for 12.0.* ? Thanks! @conda-forge/cuda-cupti

### Installed packages

```shell
.
```

### Environment info

```shell
.
```

**Comment by traversaro** [comment]
> I wonder if you would consider creating a branch `v12.0` so that I can create a PR to also fix the problem for 12.0.* ? Thanks! @conda-forge/cuda-cupti

For reference, the PR I would open on the `v12.0` is the one with this commit https://github.com/traversaro/cuda-cupti-feedstock/commit/b4cf32d8bb4ff25835b74e53ca1cd856b0c4fc3b .

**Comment by jakirkham** [comment]
Can we repodata patch the `run_exports` field? If so, that seems like the best option

**Comment by traversaro** [comment]
> Can we repodata patch the `run_exports` field? If so, that seems like the best option

I am afraid/could not understand if that is possible, as I guess the run_exports are got from the package itself, not from the repodata, but I would be happy to be wrong.

**Comment by traversaro** [comment]
By the way, I just noticed that the @conda-forge/cuda-cupti team is empty, apparently that is because the mantainer is a team:

~~~
extra:
  recipe-maintainers:
    - conda-forge/cuda
~~~

so I guess I need to mention @conda-forge/cuda instead.

**Comment by jakirkham** [comment]
cc @billysuh7 (to follow up on whether we can create a `12.0` branch and backport this fix)

**Comment by jakirkham** [comment]
Addressed in PR: https://github.com/conda-forge/cuda-cupti-feedstock/pull/20

**Comment by traversaro** [comment]
Thanks a lot!
